version: '3.1'

services:
  db:
    image: postgres:15.2
    container_name: modular_database
    restart: always
    ports:
      - '5432:5432'
    env_file: .env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
    volumes:
      - ./postgres:/var/lib/postgresql/data
